version: "3.8"

services:
  app:
    container_name: elysia_app
    build: .
    restart: always
    ports:
      - "30100:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
    depends_on:
      - db
    networks:
      - elysia_net

  db:
    image: postgres:15-alpine
    container_name: elysia_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - elysia_net

networks:
  elysia_net:
    driver: bridge

volumes:
  pgdata:
